[package]
name = "pale_image"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
image = "0.23.6"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
zstd = "0.13"